### ISSUE TITLE
What are core goals

### ISSUE THREAD

**Issue by ckeene** [Mirantis/MOM-Brain#3]
Should list the core goals for the project so we can prioritize effectivly

**Comment by boris-42** [comment]
So we should discuss do we need to keep goals in repo or it's better to keep them as a issues + label (goal) 

Let's try to create list of pros/cons here

**Comment by ckeene** [comment]
Maybe do both - have high level goals in repo so they are easy to see and separately add more detailed goals as issues + label for project tracking.

**Comment by boris-42** [comment]
Seems reasonable. 

Could you create file GOALS.yml and put your ideas in top level directory?

I would prefer to use YAML format everywhere that will simplify testing and automation (integartion with Jira) in future

**Comment by boris-42** [comment]
Closed by #8
